### ISSUE TITLE
Build fails on ubuntu18.04

### ISSUE THREAD

**Issue by leonradams** [ROCmSoftwarePlatform/rccl#115]
Following installation instruction for tensorflow at:

https://rocm-documentation.readthedocs.io/en/latest/Deep_learning/Deep-learning.html#building-pytorch-for-rocm

However rccl is not available in the ubuntu repo for 18.04.  Tried to compile following instructions on the git-repo. Installation fails at:

error: use of undeclared identifier 'hipDeviceAttributeHdpMemFlushCntl'; did you mean 'hipDeviceAttributeMemoryBusWidth'?

**Comment by saadrahim** [comment]
RCCL master and develop branches to do not work with rocm 2.6. Please use the rocm-2.6 tag for your build. The new functions calls will be available from rocm-2.8, due to be release later August or early September.

**Comment by leonradams** [comment]
I will wait on the new updates.  Thanks for your continued work.
