### ISSUE TITLE
[Issue]: top of develop cannot build with rocm 6.2 (6.4 is ok)

### ISSUE THREAD

**Issue by dmwu** [ROCmSoftwarePlatform/rccl#1763]
### Problem Description

For the top of develop branch, it only builds with rocm 6.4 or newer. Want to know if this is intended change. Not tested on 6.3 yet as we do not have it internally. The build error using rocm 6.2.1 is:
```
In file included from buck-out/v2/gen/fbsource/6fd7b6927e40d070/third-party/rccl/__generate_collectives__/out/develop/src/device/host_table.hip:1:
In file included from buck-out/v2/gen/fbsource/6fd7b6927e40d070/third-party/rccl/__rccl_objects__/buck-headers/device.h:13:
buck-out/v2/gen/fbsource/6fd7b6927e40d070/third-party/rccl/__rccl_objects__/buck-headers/rccl_float8.h:54:9: error: unknown type name '__hip_fp8_e4m3'
   54 | typedef __hip_fp8_e4m3 rccl_float8;
      |         ^
buck-out/v2/gen/fbsource/6fd7b6927e40d070/third-party/rccl/__rccl_objects__/buck-headers/rccl_float8.h:55:9: error: unknown type name '__hip_fp8_e5m2'
   55 | typedef __hip_fp8_e5m2 rccl_bfloat8;
      |         ^
buck-out/v2/gen/fbsource/6fd7b6927e40d070/third-party/rccl/__rccl_objects__/buck-headers/rccl_float8.h:63:22: error: redefinition of 'operator<<'
   63 | inline std::ostream& operator<<(std::ostream& os, const rccl_bfloat8& bf8)
      |                      ^
buck-out/v2/gen/fbsource/6fd7b6927e40d070/third-party/rccl/__rccl_objects__/buck-headers/rccl_float8.h:58:22: note: previous definition is here
   58 | inline std::ostream& operator<<(std::ostream& os, const rccl_float8& f8)
```

### Operating System

Linux 6.4

### CPU

 AMD EPYC 9654 96-Core Processor

### GPU

MI300X

### ROCm Version

6.2

### Steps to Reproduce

1. export ROCM_PATH=/path/to/rocm
2. export CXX=/path/to/rocm/bin/hipcc
3. ./install.sh -f --disable-colltrace --disable-msccl-kernel --disable-mscclpp -t 2>&1 | tee  output.txt

**Comment by nileshnegi** [comment]
looking into this
